// Mind Veda — "Mind Challenge" (16 PF form). Paid unlock: ₹300.
//
// Har item: [question, option a, option b, option c].
// Scoring key IPAT/publisher ka proprietary hota hai aur is repo me nahi hai —
// niche SCORING_KEY dekhiye. Key na hone tak answers admin ko bheje jaate hain.

export const CHALLENGE_PRICE_PAISE = 30000   // ₹300

export const INTRO = {
  title: '16 PF — Mind Challenge',
  whatToDo: `Inside this booklet are some questions to see what attitudes and interests you have. There are no "right" and "wrong" answers because everyone has the right to his own views. To be able to get the best advice from your results, you will want to answer them exactly and truly.`,
  beforeYouStart: `First you should answer the four sample questions below so that you can see whether you need to ask anything before starting. There are three possible answers to each question.`,
  points: [
    `You are asked not to spend time pondering. Give the first, natural answer as it comes to you. Of course, the questions are too short to give you all the particulars you would sometimes like to have. For instance, the sample question asks you about "team games" and you might be fonder of football than basketball. But you have to reply "for the average game", or to strike an average in situations of the kind stated. Give the best answer you can at a rate not slower than five or six a minute. You should finish in a little more than half an hour.`,
    `Try not to fall back on the middle, "uncertain" answers except when the answer at either end is really impossible for you — perhaps once every four or five questions.`,
    `Be sure not to skip anything; answer every question, somehow. Some may not apply to you very well, but give your best guess. Some may seem personal; but remember that the answer sheets are kept confidential and cannot be scored without a special stencil key. Answers to particular questions are not inspected.`,
    `Answer as honestly as possible what is true of you. Do not merely mark what seems "the right thing to say" to impress the examiner.`,
  ],
  examplesNote: `In the last example there is a right answer — kitten. But there are very few such reasoning items.`,
}

export const EXAMPLES = [
  [`I like to watch team games.`, `yes`, `occasionally`, `no`],
  [`I prefer people who:`, `are reserved`, `(are) in between`, `make friends quickly`],
  [`Money cannot bring happiness.`, `yes (true)`, `in between`, `no (false)`],
  [`Woman is to child as cat is to:`, `kitten`, `dog`, `boy`],
]

// ── 187 items ─────────────────────────────────────────────────────────────
export const ITEMS = [
  [`I have the instructions for this test clearly in mind.`, `yes`, `uncertain`, `no`],
  [`I am ready to answer each question as truthfully as possible.`, `yes`, `uncertain`, `no`],
  [`I would rather have a house:`, `in a sociable suburb`, `in between`, `alone in the deep woods`],
  [`I can find enough energy to face my difficulties.`, `always`, `generally`, `seldom`],
  [`I feel a bit nervous of wild animals even when they are in strong cages.`, `yes (true)`, `uncertain`, `no (false)`],
  [`I hold back from criticizing people and their ideas.`, `yes`, `sometimes`, `no`],
  [`I make smart, sarcastic remarks to people if I think they deserve it.`, `generally`, `sometimes`, `never`],
  [`I prefer semiclassical music to popular tunes.`, `true`, `uncertain`, `false`],
  [`If I saw two neighbors' children fighting, I would:`, `leave them to settle it`, `uncertain`, `reason with them`],
  [`On social occasions I:`, `readily come forward`, `in between`, `prefer to stay quietly in the background`],
  [`It would be more interesting to be:`, `a construction engineer`, `uncertain`, `a writer of plays`],
  [`I would rather stop in the street to watch an artist painting than listen to some people having a quarrel.`, `true`, `uncertain`, `false`],
  [`I can generally put up with conceited people, even though they brag or show they think too well of themselves.`, `yes`, `in between`, `no`],
  [`You can almost always notice on a man's face when he is dishonest.`, `yes`, `in between`, `no`],
  [`It would be good for everyone if vacations (holidays) were longer and everyone had to take them.`, `agree`, `uncertain`, `disagree`],
  [`I would rather take the gamble of a job with possibly large but uneven earnings, than one with a steady small salary.`, `yes`, `uncertain`, `no`],
  [`I talk about my feelings:`, `only if necessary`, `in between`, `readily, whenever I have a chance`],
  [`Once in a while I have a sense of vague danger or sudden dread for reasons that I do not understand.`, `yes`, `in between`, `no`],
  [`When criticized wrongly for something I did not do, I:`, `have no feeling of guilt`, `in between`, `still feel a bit guilty`],
  [`Money can buy almost everything.`, `yes`, `uncertain`, `no`],
  [`My decisions are governed more by my:`, `heart`, `feelings and reason equally`, `head`],
  [`Most people would be happier if they lived more with their fellows and did the same things as others.`, `yes`, `in between`, `no`],
  [`I occasionally get puzzled, when looking in a mirror, as to which is my right and left.`, `true`, `uncertain`, `false`],
  [`When talking, I like:`, `to say things just as they occur to me`, `in between`, `to get my thoughts well organized first`],
  [`When something really makes me furious, I find I calm down again quite quickly.`, `yes`, `in between`, `no`],
  [`With the same hours and pay, it would be more interesting to be:`, `a carpenter or cook`, `uncertain`, `a waiter in a good restaurant`],
  [`I have been elected to:`, `only a few offices`, `several`, `many offices`],
  [`"Spade" is to "dig" as "knife" is to:`, `sharp`, `cut`, `point`],
  [`I sometimes can't get to sleep because an idea keeps running through my mind.`, `true`, `uncertain`, `false`],
  [`In my personal life I reach the goals I set, almost all the time.`, `true`, `uncertain`, `false`],
  [`An out-dated law should be changed:`, `only after considerable discussion`, `in between`, `promptly`],
  [`I am uncomfortable when I work on a project requiring quick action affecting others.`, `true`, `in between`, `false`],
  [`Most of the people I know would rate me as an amusing talker.`, `yes`, `uncertain`, `no`],
  [`When I see "sloppy," untidy people, I:`, `just accept it`, `in between`, `get disgusted and annoyed`],
  [`I get slightly embarrassed if I suddenly become the focus of attention in a social group.`, `yes`, `in between`, `no`],
  [`I am always glad to join a large gathering, for example, a party, dance, or public meeting.`, `yes`, `in between`, `no`],
  [`In school I preferred (or prefer):`, `music`, `uncertain`, `handwork and crafts`],
  [`When I have been put in charge of something, I insist that my instructions are followed or else I resign.`, `yes`, `sometimes`, `no`],
  [`For parents, it is more important to:`, `help their children develop their affections`, `in between`, `teach their children how to control emotions`],
  [`In a group task I would rather:`, `try to improve arrangements`, `in between`, `keep the records and see that rules are followed`],
  [`I feel a need every now and then to engage in a tough physical activity.`, `yes`, `in between`, `no`],
  [`I would rather mix with polite people than rough, rebellious individuals.`, `yes`, `in between`, `no`],
  [`I feel terribly dejected when people criticize me in a group.`, `true`, `in between`, `false`],
  [`If I am called in by my boss, I:`, `make it a chance to ask for something I want`, `in between`, `fear I've done something wrong`],
  [`What this world needs is:`, `more steady and "solid" citizens`, `uncertain`, `more "idealists" with plans for a better world`],
  [`I am always keenly aware of attempts at propaganda in things I read.`, `yes`, `uncertain`, `no`],
  [`As a teenager, I joined in school sports:`, `occasionally`, `fairly often`, `a great deal`],
  [`I keep my room well organized, with things in known places almost all the time.`, `yes`, `in between`, `no`],
  [`I sometimes get in a state of tension and turmoil as I think of the day's happenings.`, `yes`, `in between`, `no`],
  [`I sometimes doubt whether people I am talking to are really interested in what I am saying.`, `yes`, `in between`, `no`],
  [`If I had to choose, I would rather be:`, `a forester`, `uncertain`, `a high school teacher`],
  [`For special holidays and birthdays, I:`, `like to give personal presents`, `uncertain`, `feel that buying presents is a bit of a nuisance`],
  [`"Tired" is to "work" as "proud" is to:`, `smile`, `success`, `happy`],
  [`Which of the following items is different in kind from the others?`, `candle`, `moon`, `electric light`],
  [`I have been let down by my friends:`, `hardly ever`, `occasionally`, `quite a lot`],
  [`I have some characteristics in which I feel definitely superior to most people.`, `yes`, `uncertain`, `no`],
  [`When I get upset, I try hard to hide my feelings from others.`, `true`, `in between`, `false`],
  [`I like to go out to a show or entertainment:`, `more than once a week (more than average)`, `about once a week (average)`, `less than once a week (less than average)`],
  [`I think that plenty of freedom is more important than good manners and respect for the law.`, `true`, `uncertain`, `false`],
  [`I tend to keep quiet in the presence of senior persons (people of greater experience, age, or rank).`, `yes`, `in between`, `no`],
  [`I find it hard to address or recite to a large group.`, `yes`, `in between`, `no`],
  [`I have a good sense of direction (find it easy to tell which is North, South, East, or West) when in a strange place.`, `yes`, `in between`, `no`],
  [`If someone got mad at me, I would:`, `try to calm him down`, `uncertain`, `get irritated`],
  [`When I read an unfair magazine article, I am more inclined to forget it than to feel like "hitting back."`, `true`, `uncertain`, `false`],
  [`My memory tends to drop a lot of unimportant, trivial things, for example, names of streets or stores in town.`, `yes`, `in between`, `no`],
  [`I could enjoy the life of an animal doctor, handling disease and surgery of animals.`, `yes`, `in between`, `no`],
  [`I eat my food with gusto, not always so carefully and properly as some people.`, `true`, `uncertain`, `false`],
  [`There are times when I don't feel in the right mood to see anyone.`, `very rarely`, `in between`, `quite often`],
  [`People sometimes warn me that I show my excitement in voice and manner too obviously.`, `yes`, `in between`, `no`],
  [`As a teenager, if I differed in opinion from my parents, I usually:`, `kept my own opinion`, `in between`, `accepted their authority`],
  [`I would prefer to have an office of my own, not sharing it with another person.`, `yes`, `uncertain`, `no`],
  [`I would rather enjoy life quietly in my own way than be admired for my achievements.`, `true`, `uncertain`, `false`],
  [`I feel mature in most things.`, `true`, `uncertain`, `false`],
  [`I find myself upset rather than helped by the kind of criticism that many people offer one.`, `often`, `occasionally`, `never`],
  [`I am always able to keep the expression of my feelings under exact control.`, `yes`, `in between`, `no`],
  [`In starting a useful invention, I would prefer:`, `working on it in the laboratory`, `uncertain`, `selling it to people`],
  [`"Surprise" is to "strange" as "fear" is to:`, `brave`, `anxious`, `terrible`],
  [`Which of the following fractions is not in the same class as the others?`, `3/7`, `3/9`, `3/11`],
  [`Some people seem to ignore or avoid me, although I don't know why.`, `true`, `uncertain`, `false`],
  [`People treat me less reasonably than my good intentions deserve.`, `often`, `occasionally`, `never`],
  [`The use of foul language, even when it is not in a mixed group of men and women, still disgusts me.`, `yes`, `in between`, `no`],
  [`I have decidedly fewer friends than most people.`, `yes`, `in between`, `no`],
  [`I would hate to be where there wouldn't be a lot of people to talk to.`, `true`, `uncertain`, `false`],
  [`People sometimes call me careless, even though they think I'm a likable person.`, `yes`, `in between`, `no`],
  [`"Stage-fright" in various social situations is something I have experienced:`, `quite often`, `occasionally`, `hardly ever`],
  [`When I am in a small group, I am content to sit back and let others do most of the talking.`, `yes`, `in between`, `no`],
  [`I prefer reading:`, `a realistic account of military or political battles`, `uncertain`, `a sensitive, imaginative novel`],
  [`When bossy people try to "push me around," I do just the opposite of what they wish.`, `yes`, `in between`, `no`],
  [`Business superiors or members of my family, as a rule, find fault with me only when there is real cause.`, `true`, `in between`, `false`],
  [`In streets or stores, I dislike the way some persons stare at people.`, `yes`, `in between`, `no`],
  [`On a long journey, I would prefer:`, `to read something profound, but interesting`, `uncertain`, `to pass the time talking casually with a fellow passenger`],
  [`In a situation which may become dangerous, I believe in making a fuss and speaking up even if calmness and politeness are lost.`, `yes`, `in between`, `no`],
  [`If acquaintances treat me badly and show they dislike me:`, `it doesn't upset me a bit`, `in between`, `I tend to get downhearted`],
  [`I find it embarrassing to have praise or compliments bestowed on me.`, `yes`, `in between`, `no`],
  [`I would rather have a job with:`, `a fixed, certain salary`, `in between`, `a larger salary, which depended on my constantly persuading people I am worth it`],
  [`To keep informed, I like:`, `to discuss issues with people`, `in between`, `to rely on the actual news reports`],
  [`I like to take an active part in social affairs, committee work, etc.`, `yes`, `in between`, `no`],
  [`In carrying out a task, I am not satisfied unless even the minor details are given close attention.`, `true`, `in between`, `false`],
  [`Quite small setbacks occasionally irritate me too much.`, `yes`, `in between`, `no`],
  [`I am always a sound sleeper, never walking or talking in my sleep.`, `yes`, `in between`, `no`],
  [`It would be more interesting to work in a business:`, `talking to customers`, `in between`, `keeping office accounts and records`],
  [`"Size" is to "length" as "dishonest" is to:`, `prison`, `sin`, `stealing`],
  [`AB is to dc as SR is to:`, `qp`, `pq`, `tu`],
  [`When people are unreasonable, I just:`, `keep quiet`, `uncertain`, `despise them`],
  [`If people talk loudly while I am listening to music, I:`, `can keep my mind on the music and not be bothered`, `in between`, `find it spoils my enjoyment and annoys me`],
  [`I think I am better described as:`, `polite and quiet`, `in between`, `forceful`],
  [`I attend social functions only when I have to, and stay away any other time.`, `yes`, `uncertain`, `no`],
  [`To be cautious and expect little is better than to be happy at heart, always expecting success.`, `true`, `uncertain`, `false`],
  [`In thinking of difficulties in my work, I:`, `try to plan ahead, before I meet them`, `in between`, `assume I can handle them when they come`],
  [`I find it easy to mingle among people at a social gathering.`, `true`, `uncertain`, `false`],
  [`When a bit of diplomacy and persuasion are needed to get people moving, I am generally the one asked to do it.`, `yes`, `in between`, `no`],
  [`It would be more interesting to be:`, `a guidance worker helping young people find jobs`, `uncertain`, `a manager in efficiency engineering`],
  [`If I am quite sure that a person is unjust, or behaving selfishly, I show him up, even if it takes some trouble.`, `yes`, `in between`, `no`],
  [`I sometimes make foolish remarks in fun, just to surprise people and see what they will say.`, `yes`, `in between`, `no`],
  [`I would enjoy being a newspaper writer on drama, concerts, opera, etc.`, `yes`, `uncertain`, `no`],
  [`I never feel the urge to doodle and fidget when kept sitting still at a meeting.`, `true`, `uncertain`, `false`],
  [`If someone tells me something which I know is wrong, I am more likely to say to myself:`, `"He is a liar."`, `in between`, `"Apparently he is misinformed."`],
  [`I feel some punishment is coming to me even when I have done nothing wrong.`, `often`, `occasionally`, `never`],
  [`The idea that sickness comes as much from mental as physical causes is much exaggerated.`, `yes`, `in between`, `no`],
  [`The pomp and splendor of any big state ceremony are things which should be preserved.`, `yes`, `in between`, `no`],
  [`It bothers me if people think I am being too unconventional or odd.`, `a lot`, `somewhat`, `not at all`],
  [`In constructing something I would rather work:`, `with a committee`, `uncertain`, `on my own`],
  [`I have periods when it's hard to stop a mood of self-pity.`, `often`, `occasionally`, `never`],
  [`Often I get angry with people too quickly.`, `yes`, `in between`, `no`],
  [`I can always change old habits without difficulty and without slipping back.`, `yes`, `in between`, `no`],
  [`If the earnings were the same, I would rather be:`, `a lawyer`, `uncertain`, `a navigator or pilot`],
  [`"Better" is to "worst" as "slower" is to:`, `fast`, `best`, `quickest`],
  [`Which of the following should come next at the end of this row of letters:  x o o o o x x o o o x x x`, `oxxx`, `ooxx`, `xooo`],
  [`When the time comes for something I have planned and looked forward to, I occasionally do not feel up to going.`, `true`, `in between`, `false`],
  [`I can work carefully on most things without being bothered by people making a lot of noise around me.`, `yes`, `in between`, `no`],
  [`I occasionally tell strangers things that seem to me important, regardless of whether they ask about them.`, `yes`, `in between`, `no`],
  [`I spend much of my spare time talking with friends about social events enjoyed in the past.`, `yes`, `in between`, `no`],
  [`I enjoy doing "daring," foolhardy things "just for fun."`, `yes`, `in between`, `no`],
  [`I find the sight of an untidy room very annoying.`, `yes`, `in between`, `no`],
  [`I consider myself a very sociable, outgoing person.`, `yes`, `in between`, `no`],
  [`In social contacts I:`, `show my emotions as I wish`, `in between`, `keep my emotions to myself`],
  [`I enjoy music that is:`, `light, dry, and brisk`, `in between`, `emotional and sentimental`],
  [`I admire the beauty of a poem more than that of a well-made gun.`, `yes`, `uncertain`, `no`],
  [`If a good remark of mine is passed by, I:`, `let it go`, `in between`, `give people a chance to hear it again`],
  [`I would like to work as a probation officer with criminals on parole.`, `yes`, `in between`, `no`],
  [`One should be careful about mixing with all kinds of strangers, since there are dangers of infection and so on.`, `yes`, `uncertain`, `no`],
  [`In traveling abroad, I would rather go on an expertly conducted tour than plan by myself the places I wish to visit.`, `yes`, `uncertain`, `no`],
  [`I am properly regarded as only a plodding, half-successful person.`, `yes`, `uncertain`, `no`],
  [`If people take advantage of my friendliness, I do not resent it and I soon forget.`, `true`, `uncertain`, `false`],
  [`If a heated argument developed between other members taking part in a group discussion, I would:`, `like to see a "winner"`, `in between`, `wish that it would be smoothed over`],
  [`I like to do my planning alone, without interruptions and suggestions from others.`, `yes`, `in between`, `no`],
  [`I sometimes let my actions get swayed by feelings of jealousy.`, `yes`, `in between`, `no`],
  [`I believe firmly "the boss may not always be right, but he has the right to be boss."`, `yes`, `uncertain`, `no`],
  [`I get tense as I think of all the things lying ahead of me.`, `yes`, `sometimes`, `no`],
  [`If people shout suggestions when I'm playing a game, it doesn't upset me.`, `true`, `uncertain`, `false`],
  [`It would be more interesting to be:`, `an artist`, `uncertain`, `a secretary running a club`],
  [`Which of the following words does not properly belong with the others?`, `any`, `some`, `most`],
  [`"Flame" is to "heat" as "rose" is to:`, `thorn`, `red petals`, `scent`],
  [`I have vivid dreams, disturbing my sleep.`, `often`, `occasionally`, `practically never`],
  [`If the odds are really against something's being a success, I still believe in taking the risk.`, `yes`, `in between`, `no`],
  [`I like it when I know so well what the group has to do that I naturally become the one in command.`, `yes`, `in between`, `no`],
  [`I would rather dress with quiet correctness than with eye-catching personal style.`, `true`, `uncertain`, `false`],
  [`An evening with a quiet hobby appeals to me more than a lively party.`, `true`, `uncertain`, `false`],
  [`I close my mind to well-meant suggestions of others, even though I know I shouldn't.`, `occasionally`, `hardly ever`, `never`],
  [`I always make it a point in deciding anything to refer to basic rules of right and wrong.`, `yes`, `in between`, `no`],
  [`I somewhat dislike having a group watch me at work.`, `yes`, `in between`, `no`],
  [`Because it is not always possible to get things done by gradual, reasonable methods, it is sometimes necessary to use force.`, `true`, `in between`, `false`],
  [`In school I preferred (or prefer):`, `English`, `uncertain`, `mathematics or arithmetic`],
  [`I have sometimes been troubled by people's saying bad things about me behind my back, with no grounds at all.`, `yes`, `uncertain`, `no`],
  [`Talk with ordinary, habit-bound, conventional people:`, `is often quite interesting and has a lot to it`, `in between`, `annoys me because it deals with trifles and lacks depth`],
  [`Some things make me so angry that I find it best not to speak.`, `yes`, `in between`, `no`],
  [`In education, it is more important to:`, `give the child enough affection`, `in between`, `have the child learn desirable habits and attitudes`],
  [`People regard me as a solid, undisturbed person, unmoved by ups and downs in circumstances.`, `yes`, `in between`, `no`],
  [`I think society should let reason lead it to new customs and throw aside old habits or mere traditions.`, `yes`, `in between`, `no`],
  [`I think it is more important in the modern world to solve:`, `the question of moral purpose`, `uncertain`, `the political difficulties`],
  [`I learn better by:`, `reading a well-written book`, `in between`, `joining a group discussion`],
  [`I like to go my own way instead of acting on approved rules.`, `true`, `uncertain`, `false`],
  [`I like to wait till I am sure that what I am saying is correct, before I put forth an argument.`, `always`, `generally`, `only if it's practicable`],
  [`Small things sometimes "get on my nerves" unbearably, though I realize they are trivial.`, `yes`, `in between`, `no`],
  [`I don't often say things on the spur of the moment that I greatly regret.`, `true`, `uncertain`, `false`],
  [`If asked to work with a charity drive, I would:`, `accept`, `uncertain`, `politely say I'm too busy`],
  [`Which of the following words does not belong with the others?`, `wide`, `zigzag`, `straight`],
  [`"Soon" is to "never" as "near" is to:`, `nowhere`, `far`, `away`],
  [`If I make an awkward social mistake, I can soon forget it.`, `yes`, `in between`, `no`],
  [`I am known as an "idea man" who almost always puts forward some ideas on a problem.`, `yes`, `in between`, `no`],
  [`I think I am better at showing:`, `nerve in meeting challenges`, `uncertain`, `tolerance of other people's wishes`],
  [`I am considered a very enthusiastic person.`, `yes`, `in between`, `no`],
  [`I like a job that offers change, variety, and travel, even if it involves some danger.`, `yes`, `in between`, `no`],
  [`I am a fairly strict person, insisting on always doing things as correctly as possible.`, `true`, `in between`, `false`],
  [`I enjoy work that requires conscientious, exacting skills.`, `yes`, `in between`, `no`],
  [`I'm the energetic type who keeps busy.`, `yes`, `uncertain`, `no`],
  [`I am sure there are no questions that I have skipped or failed to answer properly.`, `yes`, `uncertain`, `no`],
]

export const TOTAL_ITEMS = ITEMS.length

// 16 PF ke standard factor names — report banate waqt kaam aate hain.
export const FACTORS = [
  ['A',  'Warmth',              'Reserved — Warm'],
  ['B',  'Reasoning',           'Concrete — Abstract'],
  ['C',  'Emotional Stability', 'Reactive — Emotionally stable'],
  ['E',  'Dominance',           'Deferential — Dominant'],
  ['F',  'Liveliness',          'Serious — Lively'],
  ['G',  'Rule-Consciousness',  'Expedient — Rule-conscious'],
  ['H',  'Social Boldness',     'Shy — Socially bold'],
  ['I',  'Sensitivity',         'Utilitarian — Sensitive'],
  ['L',  'Vigilance',           'Trusting — Vigilant'],
  ['M',  'Abstractedness',      'Grounded — Abstracted'],
  ['N',  'Privateness',         'Forthright — Private'],
  ['O',  'Apprehension',        'Self-assured — Apprehensive'],
  ['Q1', 'Openness to Change',  'Traditional — Open to change'],
  ['Q2', 'Self-Reliance',       'Group-oriented — Self-reliant'],
  ['Q3', 'Perfectionism',       'Tolerates disorder — Perfectionistic'],
  ['Q4', 'Tension',             'Relaxed — Tense'],
]

// ── Scoring key ───────────────────────────────────────────────────────────
// 16 PF ka scoring stencil publisher (IPAT/PSI) ka proprietary material hai
// aur wo is repo me nahi hai. Jab tak ye null hai, site score compute nahi
// karti — answers admin ko bhej diye jaate hain, Babita apni official key se
// score karti hain.
//
// Key milne par yahan bharen:
//   SCORING_KEY = { A: { 3: [2, 1, 0], 26: [0, 1, 2], ... }, B: { ... }, ... }
// yaani factor -> { questionNumber (1-based): [aPoints, bPoints, cPoints] }
export const SCORING_KEY = null

export function scorePF16(answers) {
  if (!SCORING_KEY) return null
  const out = {}
  for (const [code] of FACTORS) {
    const map = SCORING_KEY[code]
    if (!map) continue
    let raw = 0
    for (const [qNo, pts] of Object.entries(map)) {
      const a = answers[Number(qNo) - 1]
      if (a === 0 || a === 1 || a === 2) raw += pts[a]
    }
    out[code] = raw
  }
  return out
}
