export const allServices = [
  {
    id: 1,
    slug: 'individual-counseling',
    title: 'Individual Counseling',
    icon: '🧠',
    category: 'Personal',
    price: 1500,
    duration: '45 min',
    color: 'from-purple-50 to-purple-100',
    badge: 'Most Popular',
    shortDescription: 'One-on-one support for personal challenges, emotional well-being and inner growth.',
    description: 'Individual counseling provides a safe, confidential space to explore your thoughts, feelings, and behaviors. Our certified psychologists work with you to identify patterns, develop coping strategies, and build lasting resilience for life\'s challenges.',
    benefits: ['Build emotional self-awareness', 'Overcome anxiety & low mood', 'Develop healthy coping skills', 'Improve relationships', 'Set & achieve personal goals'],
    whatToExpect: ['Initial assessment to understand your needs', 'Personalized treatment plan', 'Evidence-based therapy (CBT, DBT, etc.)', 'Exercises & tools between sessions', 'Regular progress reviews'],
  },
  {
    id: 2,
    slug: 'child-counseling',
    title: 'Child Counseling',
    icon: '🌟',
    category: 'Children',
    price: 1200,
    duration: '45 min',
    color: 'from-yellow-50 to-yellow-100',
    badge: null,
    shortDescription: 'Gentle, child-friendly support for emotional, behavioral and developmental challenges.',
    description: 'Our child counselors use age-appropriate techniques including play therapy, art and storytelling to help children express emotions, build confidence, and overcome behavioral or school-related difficulties in a safe and nurturing environment.',
    benefits: ['Improve emotional regulation', 'Build self-confidence', 'Resolve behavioral issues', 'Support school performance', 'Manage fears & social anxiety'],
    whatToExpect: ['Parent intake meeting', 'Child-friendly assessment', 'Play & creative therapy sessions', 'Parent progress updates', 'School coordination if needed'],
  },
  {
    id: 3,
    slug: 'stress-counseling',
    title: 'Stress Counseling',
    icon: '🌊',
    category: 'Personal',
    price: 1200,
    duration: '45 min',
    color: 'from-blue-50 to-blue-100',
    badge: null,
    shortDescription: 'Practical tools and strategies to manage, reduce and recover from chronic stress.',
    description: 'Chronic stress affects your body, mind and relationships. Our stress counseling sessions help you identify your stress triggers, break unhelpful thought patterns, and build a personalised toolkit of evidence-based techniques to restore calm and balance.',
    benefits: ['Identify personal stress triggers', 'Learn relaxation techniques', 'Improve sleep quality', 'Reduce physical stress symptoms', 'Build long-term resilience'],
    whatToExpect: ['Stress assessment & lifestyle review', 'Mindfulness & breathing exercises', 'Cognitive restructuring techniques', 'Work-life balance strategies', 'Ongoing support & check-ins'],
  },
  {
    id: 4,
    slug: 'career-counseling',
    title: 'Career Counseling',
    icon: '🧭',
    category: 'Career',
    price: 1500,
    duration: '45 min',
    color: 'from-green-50 to-green-100',
    badge: null,
    shortDescription: 'Find clarity, direction and confidence in your professional and academic journey.',
    description: 'Whether you\'re choosing a career path, changing fields, or struggling with work-related stress, our career counselors provide psychometric assessments, skills mapping, and goal-oriented coaching to help you make informed, confident decisions.',
    benefits: ['Discover your strengths & aptitudes', 'Explore career options clearly', 'Overcome career confusion', 'Build interview confidence', 'Set meaningful professional goals'],
    whatToExpect: ['Psychometric & aptitude assessments', 'One-on-one career exploration', 'Resume & goal planning support', 'Industry insights', 'Action plan creation'],
  },
  {
    id: 5,
    slug: 'family-counseling',
    title: 'Family Counseling',
    icon: '🏠',
    category: 'Family',
    price: 2000,
    duration: '60 min',
    color: 'from-orange-50 to-orange-100',
    badge: null,
    shortDescription: 'Restore harmony, communication and connection within your family system.',
    description: 'Family counseling helps families navigate conflict, communication breakdowns, grief, or major life transitions together. Our therapists work with all members to understand each other\'s perspectives and rebuild stronger, healthier relationships.',
    benefits: ['Improve family communication', 'Resolve long-standing conflicts', 'Navigate major life changes', 'Strengthen emotional bonds', 'Create healthy family boundaries'],
    whatToExpect: ['Family system assessment', 'Joint & individual sessions as needed', 'Communication skills training', 'Conflict resolution strategies', 'Family action planning'],
  },
  {
    id: 6,
    slug: 'sports-counseling',
    title: 'Sports Counseling',
    icon: '🏆',
    category: 'Performance',
    price: 1500,
    duration: '45 min',
    color: 'from-red-50 to-red-100',
    badge: null,
    shortDescription: 'Mental performance coaching for athletes to unlock their full competitive potential.',
    description: 'Sports psychology counseling helps athletes at all levels overcome performance anxiety, loss of motivation, injury recovery challenges, and team dynamics issues. We use proven mental performance techniques to help you compete at your best.',
    benefits: ['Overcome performance anxiety', 'Build mental toughness', 'Improve focus & concentration', 'Recover from injury setbacks', 'Strengthen team dynamics'],
    whatToExpect: ['Sports-specific mental assessment', 'Visualization & focus training', 'Pre-competition routines', 'Motivation & goal setting', 'In-season & off-season support'],
  },
  {
    id: 7,
    slug: 'anxiety-counseling',
    title: 'Anxiety Counseling',
    icon: '💆',
    category: 'Personal',
    price: 1500,
    duration: '45 min',
    color: 'from-teal-50 to-teal-100',
    badge: null,
    shortDescription: 'Evidence-based therapy to help you understand and overcome anxiety for good.',
    description: 'Anxiety counseling provides a supportive environment to explore the fears and worries that hold you back. We use evidence-based approaches like CBT to help you manage panic attacks, social anxiety, generalized anxiety, phobias, and OCD.',
    benefits: ['Reduce panic attacks', 'Manage social anxiety', 'Overcome phobias', 'Break the worry cycle', 'Build confidence in daily life'],
    whatToExpect: ['Anxiety type & severity assessment', 'CBT & exposure therapy', 'Breathing & grounding techniques', 'Thought challenging exercises', 'Relapse prevention planning'],
  },
  {
    id: 8,
    slug: 'parental-counseling',
    title: 'Parental Counseling',
    icon: '❤️',
    category: 'Family',
    price: 1500,
    duration: '45 min',
    color: 'from-pink-50 to-pink-100',
    badge: null,
    shortDescription: 'Support for parents navigating the emotional challenges of raising children.',
    description: 'Parenting is one of life\'s greatest challenges. Our parental counseling sessions help you understand your child\'s emotional needs, manage parenting stress, handle difficult behaviors with confidence, and build a deeper connection with your child.',
    benefits: ['Understand your child\'s needs', 'Manage parenting stress', 'Handle difficult behaviors', 'Improve parent-child bond', 'Build parenting confidence'],
    whatToExpect: ['Parenting style assessment', 'Child development guidance', 'Communication strategies', 'Behavior management tools', 'Ongoing coaching & support'],
  },
  {
    id: 9,
    slug: 'depression-counseling',
    title: 'Depression Counseling',
    icon: '🌱',
    category: 'Personal',
    price: 1500,
    duration: '45 min',
    color: 'from-indigo-50 to-indigo-100',
    badge: null,
    shortDescription: 'Compassionate, structured support to help you recover from depression and rediscover joy.',
    description: 'Depression is more than sadness — it affects how you think, feel, and function. Our therapists provide compassionate, evidence-based treatment to help you understand the roots of depression, rebuild energy and motivation, and reclaim your life.',
    benefits: ['Understand depression triggers', 'Rebuild daily motivation', 'Improve sleep & appetite', 'Reconnect with activities you enjoy', 'Prevent future depressive episodes'],
    whatToExpect: ['Clinical depression assessment', 'Structured therapy sessions (CBT/IPT)', 'Behavioral activation techniques', 'Mood tracking & journaling', 'Safety planning if needed'],
  },
  {
    id: 10,
    slug: 'educational-counseling',
    title: 'Educational Counseling',
    icon: '📚',
    category: 'Career',
    price: 1200,
    duration: '45 min',
    color: 'from-cyan-50 to-cyan-100',
    badge: null,
    shortDescription: 'Academic guidance and emotional support for students at every stage of education.',
    description: 'Educational counseling supports students facing academic pressure, learning difficulties, exam anxiety, or school refusal. Our counselors work with students and their families to identify barriers to learning and build effective, personalised strategies.',
    benefits: ['Overcome exam anxiety', 'Improve study habits & focus', 'Address learning difficulties', 'Build academic confidence', 'Plan higher education pathways'],
    whatToExpect: ['Academic & emotional assessment', 'Learning strategies & study plans', 'Exam preparation support', 'Parent-teacher coordination', 'Goal setting for academic success'],
  },
  {
    id: 11,
    slug: 'parent-child-counseling',
    title: 'Parent & Child Counseling',
    icon: '🤝',
    category: 'Family',
    price: 2000,
    duration: '60 min',
    color: 'from-amber-50 to-amber-100',
    badge: null,
    shortDescription: 'Joint sessions to strengthen the bond and understanding between parent and child.',
    description: 'Parent & child counseling brings parent and child together to improve communication, resolve misunderstandings, and rebuild trust. Sessions focus on developing empathy, setting healthy boundaries, and creating a more harmonious home environment.',
    benefits: ['Improve parent-child communication', 'Resolve behavioral conflicts', 'Build mutual understanding & empathy', 'Create healthy home boundaries', 'Strengthen the parent-child bond'],
    whatToExpect: ['Combined intake assessment', 'Joint & individual sessions', 'Communication skill exercises', 'Role-play & practical tools', 'Home practice tasks'],
  },
  {
    id: 12,
    slug: 'couples-counseling',
    title: "Couples' & Relationship Counseling",
    icon: '💑',
    category: 'Relationships',
    price: 2500,
    duration: '60 min',
    color: 'from-rose-50 to-rose-100',
    badge: null,
    shortDescription: 'Rebuild trust, deepen connection and resolve conflict in your relationship.',
    description: 'Couples counseling helps partners navigate conflict, rebuild intimacy, recover from betrayal, or prepare for major life changes. Our therapists create a balanced, neutral space where both partners feel heard and work toward a shared vision for the relationship.',
    benefits: ['Improve relationship communication', 'Rebuild trust after betrayal', 'Resolve recurring conflicts', 'Rekindle intimacy & connection', 'Prepare for major life transitions'],
    whatToExpect: ['Relationship history & needs assessment', 'Joint & individual sessions', 'Communication tools & exercises', 'Conflict resolution techniques', 'Shared relationship goal setting'],
  },
  {
    id: 13,
    slug: 'anxiety-support-group',
    title: 'Anxiety Support Group Online',
    icon: '🫂',
    category: 'Group',
    price: 500,
    duration: '60 min',
    color: 'from-violet-50 to-violet-100',
    badge: 'Group Session',
    shortDescription: 'A safe online community for people living with anxiety — share, learn and heal together.',
    description: 'Our facilitated online anxiety support group brings together people on similar journeys. Led by a trained psychologist, sessions combine peer sharing, psychoeducation, and coping skill practice in a warm, confidential group setting.',
    benefits: ['Reduce isolation & loneliness', 'Learn from shared experiences', 'Practice coping skills in a group', 'Build a supportive community', 'Affordable alternative to 1-on-1 therapy'],
    whatToExpect: ['Structured group sessions weekly', 'Facilitated by a certified psychologist', 'Psychoeducation & skill building', 'Peer sharing in a safe space', 'Max 10 participants per group'],
  },
  {
    id: 14,
    slug: 'depression-support-group',
    title: 'Depression Support Group Online',
    icon: '🌻',
    category: 'Group',
    price: 500,
    duration: '60 min',
    color: 'from-lime-50 to-lime-100',
    badge: 'Group Session',
    shortDescription: 'A compassionate online group for people recovering from depression — you are not alone.',
    description: 'This professionally facilitated online support group offers a safe space for people dealing with depression to connect, share experiences, and learn evidence-based tools for recovery. Every session is confidential, structured and supportive.',
    benefits: ['Feel less alone in your struggle', 'Share and receive lived-experience support', 'Learn depression management strategies', 'Build accountability & motivation', 'Low-cost peer support model'],
    whatToExpect: ['Weekly online group sessions', 'Led by experienced psychologist', 'Mood tracking & check-ins', 'Peer storytelling & sharing', 'Crisis support information provided'],
  },
]

export const servicePackages = [
  {
    id: 1,
    slug: 'yoga-wellness',
    title: 'Yoga & Wellness',
    excerpt: 'Mindful practices, breathwork and therapeutic yoga',
    price: 1999,
    duration: '45 min',
    featured: true,
  },
  {
    id: 2,
    slug: 'retreats',
    title: 'Retreats',
    excerpt: 'Immersive healing retreats in nature for deep transformation',
    price: 9999,
    duration: '2–3 days',
    featured: true,
  },
]

export const homepageServices = [
  { icon: '🪷', title: 'Individual Counseling', description: 'One-on-one support to help you navigate challenges & build a stronger you.', href: '/book/individual-counseling' },
  { icon: '❤️', title: 'Couples Therapy', description: 'Improve communication, strengthen relationships & resolve conflicts.', href: '/book/couples-counseling' },
  { icon: '🌿', title: 'Teen Counseling', description: 'Helping teens navigate emotions, identity & self-discovery.', href: '/book/child-counseling' },
  { icon: '🌊', title: 'Stress & Anxiety Support', description: 'Practical tools to manage stress and overcome overwhelm.', href: '/book/anxiety-counseling' },
  { icon: '🧭', title: 'Career Guidance', description: 'Find clarity, set meaningful goals & chart your path.', href: '/book/career-counseling' },
]

export const featuredCards = [
  {
    title: 'Online Counseling',
    description: 'Healing from the comfort of your space.',
    features: ['Secure & Confidential', 'Flexible Timing', 'HD Video Sessions'],
    href: '/services',
  },
  {
    title: 'Yoga & Wellness',
    description: 'Reconnect with your body. Calm your mind.',
    features: ['Mindfulness', 'Breathwork', 'Therapeutic Yoga'],
    href: '/packages/yoga-wellness',
  },
  {
    title: 'Healing Retreats',
    description: 'Step away. Reset. Transform.',
    features: ['Nature Immersion', 'Guided Healing Experiences', 'Digital Detox'],
    href: '/services',
  },
]

export const blogArticles = [
  {
    slug: 'morning-rituals-anxiety-work',
    category: 'Mindfulness',
    title: '5 Morning Rituals to Reduce Anxiety Before Work',
    excerpt: 'Simple grounding habits that lower stress before the day begins.',
    readTime: '6 min read',
  },
  {
    slug: 'somatic-healing-science',
    category: 'Wellness',
    title: 'The Science of Somatic Healing: How Your Body Stores Stress',
    excerpt: 'Understand how the nervous system reacts and how to reset it gently.',
    readTime: '8 min read',
  },
  {
    slug: 'healthy-boundaries-self-love',
    category: 'Relationships',
    title: 'Setting Healthy Boundaries: The Ultimate Act of Self-Love',
    excerpt: 'Boundaries can be compassionate, clear, and deeply healing.',
    readTime: '5 min read',
  },
]

export const resourceGuides = [
  {
    slug: 'anxiety-toolkit',
    title: 'Anxiety Toolkit',
    type: 'PDF Guide',
    description: 'A quick-start resource with breathing techniques, journaling prompts and calming steps.',
  },
  {
    slug: 'couples-communication-map',
    title: 'Couples Communication Map',
    type: 'Worksheet',
    description: 'A guided worksheet for better listening, repair and connection.',
  },
  {
    slug: 'self-check-in-routine',
    title: 'Self Check-in Routine',
    type: 'Audio + Notes',
    description: 'A gentle 10-minute daily routine to reconnect with your body and emotions.',
  },
]

export const testimonials = [
  { id: 1, name: 'Priya S.', role: 'Anxiety support', text: 'I was hesitant about therapy. She made me feel heard and supported.' },
  { id: 2, name: 'Rahul & Anjali D.', role: 'Couples counseling', text: 'MindVeda helped us listen to each other again and rebuild trust.' },
  { id: 3, name: 'Sandra K.', role: 'Burnout recovery', text: 'The combination of yoga and counseling helped me feel like myself again.' },
]
