-- MindVeda Supabase schema
-- Normalized structure with profiles, packages, cart, bookings, orders, blog, and resources.

create extension if not exists "pgcrypto";

-- Profiles for authenticated users
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text,
  avatar_url text,
  role text not null default 'client' check (role in ('client', 'therapist', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Service taxonomy
create table if not exists public.service_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- Core packages sold on the website
create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  category_id bigint references public.service_categories(id) on delete set null,
  slug text not null unique,
  title text not null,
  short_description text not null,
  long_description text,
  base_price numeric(10,2) not null check (base_price >= 0),
  duration_minutes int not null check (duration_minutes > 0),
  is_active boolean not null default true,
  featured_rank int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.package_features (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.packages(id) on delete cascade,
  feature_text text not null,
  sort_order int not null default 0
);

create table if not exists public.package_images (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.packages(id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order int not null default 0
);

-- Shopping cart
create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  session_token text unique,
  status text not null default 'active' check (status in ('active', 'checked_out', 'abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id uuid not null references public.carts(id) on delete cascade,
  package_id bigint not null references public.packages(id) on delete restrict,
  quantity int not null default 1 check (quantity > 0),
  unit_price numeric(10,2) not null,
  created_at timestamptz not null default now(),
  unique (cart_id, package_id)
);

-- Booking and payment flow
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  package_id bigint not null references public.packages(id) on delete restrict,
  scheduled_at timestamptz,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  cart_id uuid references public.carts(id) on delete set null,
  subtotal numeric(10,2) not null default 0,
  discount numeric(10,2) not null default 0,
  tax numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  payment_provider text,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  payment_reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  package_id bigint not null references public.packages(id) on delete restrict,
  quantity int not null default 1 check (quantity > 0),
  unit_price numeric(10,2) not null,
  line_total numeric(10,2) not null
);

-- Content tables
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_role text,
  quote text not null,
  rating int not null default 5 check (rating between 1 and 5),
  avatar_url text,
  is_featured boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.blog_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order int not null default 0
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  category_id bigint references public.blog_categories(id) on delete set null,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  content text not null,
  cover_image_url text,
  read_time_minutes int not null default 5,
  published_at timestamptz,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resource_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order int not null default 0
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  category_id bigint references public.resource_categories(id) on delete set null,
  slug text not null unique,
  title text not null,
  description text not null,
  content text,
  resource_type text not null,
  download_url text,
  cover_image_url text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Optional global settings
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- Useful indexes
create index if not exists idx_packages_category_id on public.packages(category_id);
create index if not exists idx_bookings_user_id on public.bookings(user_id);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_blog_posts_category_id on public.blog_posts(category_id);
create index if not exists idx_resources_category_id on public.resources(category_id);
create index if not exists idx_cart_items_cart_id on public.cart_items(cart_id);

-- Timestamp update helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();

drop trigger if exists trg_packages_updated_at on public.packages;
create trigger trg_packages_updated_at before update on public.packages for each row execute function public.set_updated_at();

drop trigger if exists trg_carts_updated_at on public.carts;
create trigger trg_carts_updated_at before update on public.carts for each row execute function public.set_updated_at();

drop trigger if exists trg_bookings_updated_at on public.bookings;
create trigger trg_bookings_updated_at before update on public.bookings for each row execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

drop trigger if exists trg_blog_posts_updated_at on public.blog_posts;
create trigger trg_blog_posts_updated_at before update on public.blog_posts for each row execute function public.set_updated_at();

drop trigger if exists trg_resources_updated_at on public.resources;
create trigger trg_resources_updated_at before update on public.resources for each row execute function public.set_updated_at();

-- Row level security
alter table public.profiles enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.bookings enable row level security;
alter table public.orders enable row level security;
alter table public.site_settings enable row level security;

create policy "profiles self access" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "carts owner access" on public.carts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "cart items owner access" on public.cart_items
  for all using (
    exists (
      select 1 from public.carts c
      where c.id = cart_items.cart_id and c.user_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.carts c
      where c.id = cart_items.cart_id and c.user_id = auth.uid()
    )
  );

create policy "bookings owner access" on public.bookings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "orders owner access" on public.orders
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "site settings read" on public.site_settings
  for select using (true);
